### ISSUE TITLE
Currently released pypi package doesn't match the described release on github

### ISSUE THREAD

**Issue by namelessjon** [aelzeiny/airflow-aws-executors#13]
Thanks for writing this project, it's really simplified deploying airflow for me

The release on github suggests 1.1.2 should include your modifications to allow customising the aws batch submit kwargs, however this code isn't included with the pypi release.

Would it be possible to cut a new release reflecting this, please?

**Comment by aelzeiny** [comment]
Repackaged release & closing out this issue now. Thank you for your time, sorry for the late reply.

**Comment by namelessjon** [comment]
Thanks!
